### ISSUE TITLE
extract-files.sh does not work properly

### ISSUE THREAD

**Issue by Meetoul** [ADeadTrousers/twrp_device_Unihertz_Atom_LXL#5]
Does extract-files.sh generates correct vendor/Unihertz/Jelly2_TEE/DEVICE-vendor.mk in you environment?

When I run it, I got $(TARGET_COPY_OUT_SYSTEM)/recovery/root/vendor in PRODUCT_COPY_FILES which is invalid path, so the files are not copied. In order to fix it, I manually changed it to $(TARGET_COPY_OUT_ROOT)/vendor and the files are properly copied after the change.

Am I doing something wrong?

Btw, thank you so much for publishing this. I'm using it as TWRP base for my Jelly2. Now I have bootable recovery with working touch, but still fighting with data encryption :) I will publish the sources too, once I got success with data encryption.

**Comment by Meetoul** [comment]
I realized that I hadn't applied the patches to the source tree, so the path was wrong.

Sorry for creating the issue, I close this one.

**Comment by ADeadTrousers** [comment]
No problem.
If you need help with encryption just write me an email.
It took me half a year until I figured everything out and I lost nearly all my data once (google backup didn't work for some unknown reason). Maybe I can save you some time ;)
